name: my-cicd

on:
  workflow_dispatch:
  
env:
  NAME: Akhil
jobs:
  demo:
   runs-on: ubuntu-latest
   steps:
    - run: echo "Environment: $NAME"
    - name: Checkout
      uses: actions/checkout@v7.0.1 
      
    - name: list the contents
      run: ls -a

    - name: path
      run: pwd
